package com.pktap.app.keystore

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Manages the AES-256-GCM key in Android Keystore used to encrypt the HKDF seed.
 *
 * Security properties (D-01, D-02, KEY-02, KEY-05, T-04-01, T-04-03, T-04-07):
 * - Key is non-extractable (stays in hardware security module)
 * - StrongBox attempted first on API 28+; falls back to TEE on older APIs or unavailable hardware
 * - GCM IV is auto-generated by Keystore on each encrypt (never reused — T-04-03)
 * - Only operation names are logged — never byte values (T-04-02)
 */
object KeystoreManager {

    private const val TAG = "KeystoreManager"
    const val SEED_KEY_ALIAS = "pktap_aes_key"

    /**
     * Return the existing Keystore AES key for [alias], or generate a new one.
     *
     * On API 28+, attempts StrongBox first. On StrongBoxUnavailableException, falls back to TEE.
     * On API 26-27, skips StrongBox entirely (setIsStrongBoxBacked not available — T-04-07).
     */
    fun generateOrGetKey(alias: String): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        keyStore.getKey(alias, null)?.let { return it as SecretKey }

        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
                createKey(alias, strongBox = true).also {
                    Log.d(TAG, "Key generated via StrongBox")
                }
            } catch (e: StrongBoxUnavailableException) {
                Log.d(TAG, "StrongBox unavailable, falling back to TEE")
                createKey(alias, strongBox = false).also {
                    Log.d(TAG, "Key generated via TEE")
                }
            }
        } else {
            // API 26-27: StrongBoxUnavailableException and setIsStrongBoxBacked not available
            createKey(alias, strongBox = false).also {
                Log.d(TAG, "Key generated via TEE (API < 28, StrongBox skipped)")
            }
        }
    }

    private fun createKey(alias: String, strongBox: Boolean): SecretKey {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            "AndroidKeyStore"
        )
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .apply {
                if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    setIsStrongBoxBacked(true)
                }
            }
            .build()
        keyGenerator.init(spec)
        return keyGenerator.generateKey()
    }

    /**
     * Encrypt [plaintext] with [key] using AES/GCM/NoPadding.
     *
     * The IV is auto-generated by the Keystore Cipher (never reused — T-04-03).
     * Returns a string in the format: "base64(iv):base64(ciphertext+tag)".
     *
     * Caller MUST zero [plaintext] in a finally block after this call returns (T-04-01).
     */
    fun encrypt(plaintext: ByteArray, key: SecretKey): String {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val ciphertext = cipher.doFinal(plaintext)
        val iv = cipher.iv  // 12 bytes for GCM, auto-generated
        return "${Base64.encodeToString(iv, Base64.NO_WRAP)}:${Base64.encodeToString(ciphertext, Base64.NO_WRAP)}"
    }

    /**
     * Decrypt a value produced by [encrypt].
     *
     * @param stored String in "base64(iv):base64(ciphertext+tag)" format
     * @param key The same AES key used during encryption
     * @return Decrypted plaintext bytes — caller MUST zero in a finally block (T-04-01)
     */
    fun decrypt(stored: String, key: SecretKey): ByteArray {
        val parts = stored.split(":")
        val iv = Base64.decode(parts[0], Base64.NO_WRAP)
        val ciphertext = Base64.decode(parts[1], Base64.NO_WRAP)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(128, iv))
        return cipher.doFinal(ciphertext)
    }
}
